# Generated by Django 5.2.17 on 2026-08-24 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_cafe_stay_color_stops"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("visitor_count", models.PositiveIntegerField(default=0)),
                ("ended_session_count", models.PositiveIntegerField(default=0)),
                ("total_stay_seconds", models.FloatField(default=0.0)),
                ("average_stay_seconds", models.FloatField(blank=True, null=True)),
                ("longest_stay_seconds", models.FloatField(blank=True, null=True)),
                ("hourly_entries", models.JSONField(default=list)),
                ("peak_occupancy", models.PositiveIntegerField(default=0)),
                ("peak_occupancy_at", models.DateTimeField(blank=True, null=True)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.cafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily stat",
                "verbose_name_plural": "daily stats",
                "ordering": ("-date",),
                "indexes": [
                    models.Index(
                        fields=["cafe", "-date"], name="dailystat_cafe_date_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cafe", "date"), name="unique_daily_stat_per_cafe_day"
                    )
                ],
            },
        ),
    ]
