# Generated by Django 5.2.17 on 2026-08-24 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_cafe_stay_color_stops"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("camera_id", models.UUIDField(db_index=True)),
                ("table_zone_id", models.UUIDField(db_index=True)),
                ("table_name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("ended", "Ended")],
                        db_index=True,
                        default="active",
                        max_length=8,
                    ),
                ),
                ("occupied_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cleared", "Occupancy cleared"),
                            ("stale", "Worker went quiet"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("last_seen_at", models.DateTimeField()),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.cafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "table session",
                "verbose_name_plural": "table sessions",
                "ordering": ("-occupied_at",),
                "indexes": [
                    models.Index(
                        fields=["cafe", "status", "-occupied_at"],
                        name="tablesess_cafe_status_idx",
                    ),
                    models.Index(
                        fields=["table_zone_id", "status"],
                        name="tablesess_table_status_idx",
                    ),
                ],
            },
        ),
    ]
