import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // An underscore prefix is the conventional marker for "destructured only
      // to strip it from an object" — as in api.ts, where `authenticated` must
      // not reach fetch().
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
    },
  },
  // next-env.d.ts is generated by Next and uses triple-slash references by
  // design; linting a file we do not author has no upside.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
];

export default config;
