# Generated by Django 5.2.17 on 2026-08-23 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("camera_id", models.UUIDField(db_index=True)),
                ("track_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("ended", "Ended")],
                        db_index=True,
                        default="active",
                        max_length=8,
                    ),
                ),
                ("entry_at", models.DateTimeField()),
                (
                    "entry_zone_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("exit_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exit_zone_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("line_crossing", "Crossed an exit line"),
                            ("track_lost", "Tracker lost the person"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("last_seen_at", models.DateTimeField()),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.cafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer session",
                "verbose_name_plural": "customer sessions",
                "ordering": ("-entry_at",),
                "indexes": [
                    models.Index(
                        fields=["cafe", "status", "-entry_at"],
                        name="sess_cafe_status_entry_idx",
                    ),
                    models.Index(
                        fields=["camera_id", "track_id", "status"],
                        name="sess_camera_track_status_idx",
                    ),
                ],
            },
        ),
    ]
