# Generated by Django 5.2.17 on 2026-08-18 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=48)),
                ("event_id", models.UUIDField(unique=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("camera_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("worker_id", models.CharField(blank=True, default="", max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.cafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "tracking event",
                "verbose_name_plural": "tracking events",
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["cafe", "event_type", "-occurred_at"],
                        name="evt_cafe_type_time_idx",
                    ),
                    models.Index(
                        fields=["cafe", "camera_id", "-occurred_at"],
                        name="evt_cafe_cam_time_idx",
                    ),
                ],
            },
        ),
    ]
