# Generated by Django 5.2.17 on 2026-08-23 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_cafe_stay_color_stops"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_en", models.CharField(max_length=200)),
                ("text_fa", models.CharField(blank=True, default="", max_length=200)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to remove a message from rotation without deleting it.",
                    ),
                ),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.cafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "display message",
                "verbose_name_plural": "display messages",
                "ordering": ("created_at",),
            },
        ),
    ]
