# Generated by Django 5.2.17 on 2026-08-18 21:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier, e.g. used in /display/<slug>.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="cafe-logos/"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA name, e.g. Europe/Berlin or Asia/Tehran.",
                        max_length=64,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("en", "English"), ("fa", "Persian")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "seating_capacity",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="Used as the denominator for occupancy percentage.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "privacy_notice_en",
                    models.TextField(
                        blank=True,
                        default="This café uses anonymous camera analytics to measure how busy it is. No faces are recognised, no identities are stored, and no footage is kept.",
                    ),
                ),
                (
                    "privacy_notice_fa",
                    models.TextField(
                        blank=True,
                        default="این کافه از تحلیل تصویری ناشناس برای اندازه\u200cگیری شلوغی استفاده می\u200cکند. هیچ چهره\u200cای شناسایی نمی\u200cشود، هیچ هویتی ذخیره نمی\u200cشود و هیچ تصویری نگهداری نمی\u200cشود.",
                    ),
                ),
            ],
            options={
                "verbose_name": "café",
                "verbose_name_plural": "cafés",
                "ordering": ("name",),
            },
        ),
    ]
