# Generated by Django 5.2.17 on 2026-08-23 21:05

import apps.core.color
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="stay_color_stops",
            field=models.JSONField(
                default=apps.core.color.default_stay_color_stops,
                help_text="Colour stops for stay-time display, e.g. green when a customer just arrived, sliding to red the longer they stay.",
                validators=[apps.core.color.validate_color_stops],
            ),
        ),
    ]
