# Generated by Django 5.2.17 on 2026-08-27 15:41

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_cafe_stay_color_stops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cafe-logos/",
                validators=[apps.tenants.models.validate_logo_size],
            ),
        ),
    ]
