# Generated by Django 5.2.17 on 2026-08-22 09:29

import apps.cameras.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='', help_text='e.g. Entrance, Main hall', max_length=120)),
                ('rtsp_url', models.CharField(help_text='rtsp://host:port/path — no username or password in the URL.', max_length=500, validators=[apps.cameras.validators.validate_rtsp_url])),
                ('rtsp_username', models.CharField(blank=True, default='', max_length=128)),
                ('rtsp_password_encrypted', models.CharField(blank=True, default='', max_length=512)),
                ('transport', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=8)),
                ('is_enabled', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='unknown', max_length=16)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_frame_at', models.DateTimeField(blank=True, null=True)),
                ('last_fps', models.FloatField(blank=True, null=True)),
                ('resolution_width', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_height', models.PositiveIntegerField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.cafe')),
            ],
            options={
                'verbose_name': 'camera',
                'verbose_name_plural': 'cameras',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('cafe', 'name'), name='unique_camera_name_per_cafe')],
            },
        ),
    ]
