# Generated by Django 5.2.17 on 2026-08-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="last_inference_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="last_person_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
