# Generated by Django 5.2.17 on 2026-08-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0002_camera_last_inference_ms_camera_last_person_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="last_track_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
