# Generated by Django 5.2.17 on 2026-08-23 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0003_camera_last_track_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Entrance", max_length=120)),
                ("point_a_x", models.FloatField()),
                ("point_a_y", models.FloatField()),
                ("point_b_x", models.FloatField()),
                ("point_b_y", models.FloatField()),
                ("entry_is_positive_side", models.BooleanField(default=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop entry/exit detection on this line without deleting it.",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "zone",
                "verbose_name_plural": "zones",
                "ordering": ("name",),
            },
        ),
    ]
