# Generated by Django 5.2.17 on 2026-08-24 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cameras", "0004_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="mount_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("overhead", "Overhead"),
                    ("wall", "Wall-mounted"),
                ],
                default="unknown",
                help_text="Affects how confidently table occupancy is reported for this camera's tables.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="TableZone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Table", max_length=120)),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("x2", models.FloatField()),
                ("y2", models.FloatField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to stop occupancy detection on this table without deleting it.",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "table",
                "verbose_name_plural": "tables",
                "ordering": ("name",),
            },
        ),
    ]
